### ISSUE TITLE
Extra inputs to CALLB PRINT in DISASM

### ISSUE THREAD

**Issue by steve64** [endbasic/endbasic#245]
Not probably an issue, but a request for clarification.
I'm playing with the DISASM output.
What's the meaning of the extra pushed arguments before a CALLB PRINT, n ?
For instance:
PRINT 10; 20; 30
leads to:
PUSH% 30
PUSH% 3 # ???
PUSH% 1 # ???
PUSH% 20
PUSH% 3 # ???
PUSH% 1 # ???
PUSH% 10
CALLB PRINT, 8
I can suppose they are internal flags to control the printing...

More generally, are you planning to publish a spec of the bytecode?

**Comment by jmmv** [comment]
Those numbers pushed onto the stack are tags. `PRINT` has a very complicated syntax where commas and semicolons have meaning and where arguments can be of any type and may be present or not. So these tags encode the meaning of the separators and the type of the following arguments.

The syntax definition for the command is at https://github.com/endbasic/endbasic/blob/6484f66917efad3a71a135ab67773aa65dc28a2d/std/src/console/cmds.rs#L502 and then there is this monster parser at https://github.com/endbasic/endbasic/blob/6484f66917efad3a71a135ab67773aa65dc28a2d/core/src/compiler/args.rs#L534 to convert the arguments into stack values.

I hadn't thought about documenting the bytecode just yet because it's still in flux and it's not that useful on its own. Ideally, I'd like to polish the VM internals first to remove the typed stack (which requires adding a heap for strings and arrays), and then offer a way to *assemble* bytecode directly from the environment. The latter would be neat, and it's when you'd need documentation :)

**Comment by steve64** [comment]
Generating the bytecode directly as command line option for the endbasic interpreter would be helpful, if this is what you meant. Please keep also the textual version since easier to parse.
I'm trying to generate proprietary native code from the bytecode for an embedded processor. So the bytecode spec is useful for my scenario. I understand is still fluid, but at this stage I may survive with changes. About removing the typed stack, I'm not sure it will help me. It seems fine as is now. If not typed it will be difficult to transpile to native code.
